import mongoose from "mongoose";

const userSchema = new mongoose.Schema(
  {
    clerkId: { type: String, required: true, unique: true }, // Store Clerk ID separately
    name: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    resume: { type: String, default: "" },
    image: { type: String, required: true },
  },
  { timestamps: true }
);

// Ensure `_id` is auto-generated by MongoDB
const User = mongoose.model("User", userSchema);

export default User;
